version: '3'

# Attention.
# First time you should start database container. 
# It will create database. Only after that - start jira and proxy. 
# for example: 
# > docker-compose up jiradb
# wait fey seconds (check logs) and start as usual.
# > docker-compose up -d

services:
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - ./certs/:/etc/nginx/certs:ro
      - ./jira-nginx_mysql.conf:/etc/nginx/vhost.d/jira.local.net
    networks:
      - proxy
  jiradb:
    image: mysql/mysql-server:5.6
    command: --character-set-server=utf8 --collation-server=utf8_bin
    # you can use utf8mb4 only with mysql 5.7 
    # https://confluence.atlassian.com/jirakb/emojis-and-special-characters-for-jira-with-mysql-952604493.html
    volumes:
      - jiradb:/var/lib/mysql
    # ./simple-jira-data.sql:/docker-entrypoint-initdb.d/initdb.sql
    # 
    # When a container is started for the first time, a new database with the specified name will be created and 
    # initialized with the provided configuration variables. Furthermore, it will execute files with extensions 
    # .sh, .sql and .sql.gz that are found in /docker-entrypoint-initdb.d. Files will be executed in alphabetical order. 
    # You can easily populate your mysql services by mounting a SQL dump into that directory and provide custom images with contributed data. 
    # SQL files will be imported by default to the database specified by the MYSQL_DATABASE variable.
    # https://hub.docker.com/_/mysql/
    environment:
      - MYSQL_PASSWORD=atlassian
      - MYSQL_DATABASE=jira
      - MYSQL_USER=atlassian
    networks:
      - jira
  jira:
    image: q2digger/jira-software:latest
    restart: on-failure
    ports: 
      - 0.0.0.0:8080:8080
    volumes:
      - jiradata:/var/atlassian/jira
      - jiralogs:/opt/atlassian/jira/logs
      - ./jira.config_mysql:/opt/atlassian/jira/conf/jira.config
      - ./certs/:/ssl/root
    networks:
      - jira
      - proxy
    environment:
      JVM_MINIMUM_MEMORY: '2048m'
      JVM_MAXIMUM_MEMORY: '4096m'
      CATALINA_CONNECTOR_PROXYNAME: 'jira.local.net'
      CATALINA_CONNECTOR_PROXYPORT: '443'
      CATALINA_CONNECTOR_SCHEME: 'https'
      VIRTUAL_HOST: 'jira.local.net'
      VIRTUAL_PORT: '8080'

volumes:
  jiradb:
  jiradata:
  jiralogs:

networks:
  jira:
  proxy:
