version: '2'

services:
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - ./certs/:/etc/nginx/certs:ro
      - ./jira-nginx.conf:/etc/nginx/vhost.d/jira.local.net
    networks:
      - proxy
  jiradb:
    image: blacklabelops/postgres
    volumes:
      - _jiradb:/var/lib/postgresql/data
    # ./init-db-data.sql:/docker-entrypoint-initdb.d/initdb.sql
    # load init data during deploy db container
    # https://hub.docker.com/_/postgres 
    # chapter "How to extend this image"
    environment:
      - POSTGRES_PASSWORD=atlassian
      - POSTGRES_DB=jira
      - POSTGRES_USER=atlassian
      - POSTGRES_ENCODING=UNICODE
      - POSTGRES_COLLATE=C
      - POSTGRES_COLLATE_TYPE=C
    networks:
      - jira
  jira:
    image: q2digger/jira-software:latest
    ports: 
      - 0.0.0.0:8080:8080
    volumes:
      - _jiradata:/var/atlassian/jira
      - _jiralogs:/opt/atlassian/jira/logs
      - ./jira.config:/opt/atlassian/jira/conf/jira.config
      - ./certs/:/ssl/root
    networks:
      - jira
      - proxy
    environment:
      JVM_MINIMUM_MEMORY: '2048m'
      JVM_MAXIMUM_MEMORY: '4096m'
      CATALINA_CONNECTOR_PROXYNAME: 'jira.local.net'
      CATALINA_CONNECTOR_PROXYPORT: '443'
      CATALINA_CONNECTOR_SCHEME: 'https'
      VIRTUAL_HOST: 'jira.local.net'
      VIRTUAL_PORT: '8080'

volumes:
  _jiradb:
  _jiradata:
  _jiralogs:

networks:
  jira:
  proxy:
